[package]
name = "guessing-game"
version = "0.1.0"
authors = ["Jose <huguanzhou123@sina.com>"]
edition = "2018"

[dependencies]
rand = "0.6"

[profile.dev]
opt_level = 1

[profile.release]
opt_level = 3